### ISSUE TITLE
Reconsider floating point configuration strategy (`Real`)

### ISSUE THREAD

**Issue by torkleyy** [Rhuagh/rhusics#43]
Currently there's a `Real` type which can be either `f32` or `f64` depending on a feature flag. This however does not match Rust's concept of features; they're additive, meaning that adding a dependency and/or a feature requirement shall never result in a compilation error.

Another disadvantage the current strategy has is that it is impossible to use `rhusics` with 32-bit floating-point logic **and** 64-bit floating-point logic.

**Comment by Rhuagh** [comment]
It's on the list yeah.

**Comment by torkleyy** [comment]
Yeah I know we discussed it before, just wanted to create an issue so we don't forget it or maybe somebody else can pick it up.

**Comment by Rhuagh** [comment]
Done.
